LogInfo:
  Level: DEBUG #DEBUG,ERROR, INFO
  OutPaths: ./logs/

RtmpServer:
  ClusterCnf: ["127.0.0.1:1935"]
  SelfIp: "127.0.0.1:1935"
  RtmpListen: [":1935","/tmp/rtmp.socket8"]
  HttpListen: [":8087","/tmp/http.socket6"]
  QuicListen: ":444"
  KcpListen: ":9997"
  QuicPush: 1

UserConf:
  PublishDomain:
    test.uplive.com:
      UniqueName: test
      App:
        live:
          GopCacheNum: 2
          ExtTimeSend: 1
          RecodeFlv: 0
          RecodeHls: 0
          hlsFragment: "5s"
          RecodeFlvPath: "/dev/shm/data/flv"
          RecodeHlsPath: "/data/hls"
          RecodePicture: 0
          TurnHost: ["test.uplive.com/test"]
        test:
          GopCacheNum: 1
          RecodeHls: 0
          hlsFragment: "5s"
          RecodeFlvPath: "/dev/shm/data/flv"
          RecodeHlsPath: "/data/hls"
          RecodePicture: 0
        test1:
          GopCacheNum: 1
          RecodeFlv: 0
          RecodeHls: 0
          hlsFragment: "5s"
          RecodeFlvPath: "/data/flv"
          RecodeHlsPath: "/data/hls"
          RecodePicture: 0
  PlayDomain:
    test.live.com:
      UniqueName: test
      App:
        live:

